export enum types {
  USER_REGISTERED = "USER_REGISTERED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_HEARTS_GOT = "USER_HEARTS_GOT",
  USER_HEARTS_TOGGLED = "USER_HEARTS_TOGGLED",
  USER_UPDATE_INFO = "USER_UPDATE_INFO",
  USERS_ADDED = "USERS_ADDED",
  FLASH_SUCCESS = "FLASH_SUCCESS",
  FLASH_ERROR = "FLASH_ERROR",
  FLASH_WARNING = "FLASH_WARNING",
  FLASH_TOGGLE = "FLASH_TOGGLE",
  FLASH_CLOSE = "FLASH_CLOSE",
  REVIEWS_ADDED = "REVIEWS_ADDED",
  SAUCE_ADDED = "SAUCE_ADDED",
  SAUCES_UPDATE_ITEM = "SAUCES_UPDATE_ITEM",
  SAUCES_BY_TAG_FOUND = "SAUCES_BY_TAG_FOUND",
  SAUCES_SINGLE_FOUND = "SAUCES_SINGLE_FOUND"
}
